### ISSUE TITLE
a downloadable version

### ISSUE THREAD

**Issue by AndresVoxd** [SophieShears/MidiToChiptune#2]
I think that a downloadable version would be better, since the browser limits the program and sometimes the audio is not heard or it sounds very corrupt, I don't know if there is a downloadable version, but if there isn't, there has to be one, apart from that I would like one option to download the song either in mp4 or wav, as it becomes easier for programmers

I'm sorry for my bad English, I'm looking for a translator

**Comment by SophieShears** [comment]
Completed in #3
